CONFIG_VMR=m

obj-$(CONFIG_VMR) += kvirtual.o
obj-$(CONFIG_VMR) += pagemap.o
obj-$(CONFIG_VMR) += sizes.o
obj-$(CONFIG_VMR) += trace_alloccount.o
obj-$(CONFIG_VMR) += trace_allocmap.o
obj-$(CONFIG_VMR) += zone.o

EXTRA_CFLAGS += -I$(src)/../../include
